# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\"\x1f\n\x07Numeros\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1e\n\tResultado\x12\x11\n\tresultado\x18\x01 \x01(\x05\x32L\n\x0b\x43\x61lculadora\x12\x1c\n\x04Soma\x12\x08.Numeros\x1a\n.Resultado\x12\x1f\n\x07Subtrai\x12\x08.Numeros\x1a\n.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMEROS']._serialized_start=21
  _globals['_NUMEROS']._serialized_end=52
  _globals['_RESULTADO']._serialized_start=54
  _globals['_RESULTADO']._serialized_end=84
  _globals['_CALCULADORA']._serialized_start=86
  _globals['_CALCULADORA']._serialized_end=162
# @@protoc_insertion_point(module_scope)
